#!/bin/sh -e

BUILD_DIR=
CUR_DIR=$(dirname "$(readlink -f "$0")")

if [ $# -ge 2 ]
then
    case $1 in
        -b|--build)
        BUILD_DIR=$2
        shift
        shift
        ;;
        *)
        ;;
    esac
fi

if [ -n "$BUILD_DIR" ]
then
    echo "Using WPE build directory: $BUILD_DIR"
    export LD_LIBRARY_PATH=$BUILD_DIR/lib:$LD_LIBRARY_PATH
    export WEBKIT_EXEC_PATH=$BUILD_DIR/bin
fi

export LD_LIBRARY_PATH=$CUR_DIR/src:$LD_LIBRARY_PATH
export LUA_PATH="$CUR_DIR/src/?.lua"

exec "$CUR_DIR/src/dyz" "$@"
